[JENKINS-63727] Add support to convey compatibility info related to JGit and Git Publisher
jenkinsci/git-client-plugin pull request #615
Opened 2020-09-21 08:45 UTC by rishabhBudhouliya

## [JENKINS-63727](https://issues.jenkins-ci.org/browse/JENKINS-63727) - Add support to convey compatibility info related to JGit and Git Publisher

The UnsupportedCommand now features a support to convey if JGit should be suggested
as a viable implementation in the scenario where Git Publisher is added as a post build
action.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-client-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [ ] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [x] I have interactively tested my changes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

2020-09-21 19:32 UTC, MarkEWaite requested changes
Needs Javadoc to avoid a pair of Javadoc warnings

2020-09-21 19:32 UTC, MarkEWaite commented on src/main/java/org/jenkinsci/plugins/gitclient/UnsupportedCommand.java
> +     * JGit doesn't support Git Publisher
```suggestion
     * JGit doesn't support Git Publisher.
     * @param isEnabled if true, then git publisher post-build action is enabled in this context
     * @return this for chaining
```

2020-09-22 01:03 UTC, MarkEWaite approved these changes

2020-09-22 04:48 UTC, merged

2020-09-22 05:20 UTC, rishabhBudhouliya commented
@MarkEWaite Apologies for not being able to add your suggestions in due time, many thanks for doing so!