Migrating tests of GitAPITestCase from JUnit 3 to JUnit 4
jenkinsci/git-client-plugin pull request #674
Opened 2021-02-23 04:27 UTC by GAyan17

## [JENKINS-60940](https://issues.jenkins-ci.org/browse/JENKINS-60940) - Migrating tests of GitAPITestCase from JUnit 3 to JUnit 4

In this PR, the test migrated is:
- testCleanWithParameters

Describe the big picture of your changes here to explain to the maintainers why this pull request should be accepted.
If it fixes a bug or resolves a feature request, include a link to the issue.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-client-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [ ] I have interactively tested my changes

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

- [x] Tests
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

2021-02-23 05:17 UTC, MarkEWaite requested changes
Needs to have the changes reverted that are purely white space.  White space changes make other pull requests have unnecessary conflicts.  See the CONTRIBUTING file for more details describing why this plugin needs to leave its ugly formatting alone.

2021-02-23 05:17 UTC, MarkEWaite commented on src/test/java/org/jenkinsci/plugins/gitclient/WorkspaceWithRepo.java
> +     * @throws IOException          on I/O error
Please don't make whiitespace changes to existing files.  It creates unnecessary barriers to other pull requests.
```suggestion
     * @throws IOException on I/O error
```

2021-02-23 05:17 UTC, MarkEWaite commented on src/test/java/org/jenkinsci/plugins/gitclient/WorkspaceWithRepo.java
> +            throws Exception {
Please don't make white space changes in existing files.  It creates barriers for other pull requests.
```suggestion
    private GitClient setupGitClient(File gitFileDir, @NonNull String gitImplName, TaskListener listener) throws Exception {
```

2021-02-23 05:17 UTC, MarkEWaite commented on src/test/java/org/jenkinsci/plugins/gitclient/WorkspaceWithRepo.java
> +                            tempClonePath.toFile().getAbsolutePath());
Please remove the pure white space changes in the existing files.
```suggestion
                    cliGitCommand.run("clone", "--reference", f.getCanonicalPath(), "--mirror", repoURL, tempClonePath.toFile().getAbsolutePath());
```

2021-02-23 05:28 UTC, GAyan17 commented
Thanks @MarkEWaite for the code suggestion review, I will surely keep that in mind for other pull requests.

2021-02-24 04:17 UTC, MarkEWaite approved these changes

2021-02-24 05:04 UTC, merged