[JENKINS-23606](https://issues.jenkins.io/browse/JENKINS-23606) - remove unnecessary -m flag in CliGitAPIImpl.showRevision
jenkinsci/git-client-plugin pull request #750
Opened 2021-09-15 00:45 UTC by anatoly-spb

The -m flag breaks polling changes mechanism, for example: 

https://issues.jenkins.io/browse/JENKINS-23606
https://issues.jenkins.io/browse/JENKINS-36180
https://issues.jenkins.io/browse/JENKINS-65932

This is pull request fix this issue.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x ] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-client-plugin/blob/master/CONTRIBUTING.adoc) doc
- [ x] I have referenced the Jira issue related to my changes in one or more commit messages
- [  ] I have added tests that verify my changes
- [ ] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [ ] No Javadoc warnings were introduced with my changes
- [ ] No spotbugs warnings were introduced with my changes
- [ ] I have interactively tested my changes

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

- [ ] Infrastructure change (non-breaking change which updates dependencies or improves infrastructure)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-09-15 01:52 UTC, MarkEWaite commented
The change breaks compatibility as shown by the automated test that fails.  It will need to be a flag that is passed into the API rather than an "always on" change.  The default of the flag will need to be "off" so that we don't break compatibility for users.

2021-09-15 01:54 UTC, MarkEWaite requested changes
This will break compatibility with existing use cases.  It needs to be only enabled when a new argument is toggled to enable the new behavior.

2021-09-15 02:25 UTC, anatoly-spb commented
> This will break compatibility with existing use cases. It needs to be only enabled when a new argument is toggled to enable the new behavior.

Thank you @MarkEWaite. May be you know where is polling change mechanism implemented to call showRevision  with additional argument?

2021-09-15 03:54 UTC, MarkEWaite commented
Yes, that sounds about right.  Include tests to confirm the old behavior and the new behavior

2021-12-02 16:32 UTC, anatoly-spb commented
@MarkEWaite are you going to merge this request or what should I do to push this work will be done?

2021-12-05 00:27 UTC, MarkEWaite commented
> ... Include tests to confirm the old behavior and the new behavior

@anatoly-spb as far as I can tell, you have not created any tests to confirm the new behavior is what you expect.  The existing behavior might be covered by existing tests, but the new behavior is not covered by tests.  Without tests, it is far too easy for a later change to undo or damage the behavior that you want.  Please provide tests

2021-12-05 00:44 UTC, MarkEWaite requested changes
Needs tests to confirm new behavior and to assure that current behavior is retained

2023-02-04 01:54 UTC, MarkEWaite commented
Closing because tests have not been added to confirm the new behavior works as expected.

2023-02-04 01:54 UTC, closed without merging

2023-03-03 14:44 UTC, anatoly-spb commented
> Closing because tests have not been added to confirm the new behavior works as expected.

Could you help me to add such tests?

2023-10-11 13:03 UTC, murerfel commented
Any chances this will get re-opened and re-evaluated? It seems it would fix a problem that has been plaguing us for years now (https://issues.jenkins.io/browse/JENKINS-23606)

2023-10-11 13:22 UTC, MarkEWaite commented
> Any chances this will get re-opened and re-evaluated? It seems it would fix a problem that has been plaguing us for years now (https://issues.jenkins.io/browse/JENKINS-23606)

With my current workload, there is no chance that I will reopen it and re-evaluate it.  Others are welcome to reopen it and re-evaluate it, but my workload does not allow me to do the additional work needed on this pull request.

@anatoly-spb indicated that new tests have not been added because help is needed to create those new tests.  I don't have capacity right now to create those new tests.  If others would like to create those new tests and report that they have deployed the incremental build of the plugin into production, that would might persuade me or other maintainers of the plugin to evaluate the changes.

@murerfel are you willing to add the new tests, merge the latest changes from the master branch, deploy an incremental build into your environment, and report the results here?

2023-10-11 13:55 UTC, murerfel commented
Thank you, @MarkEWaite, the quick response is appreciated. Unfortunately, I have neither the required expertise nor the resources for such an endeavor at this point. So we'll just have to be patient for now.